
** BUILD SYSTEMS
*** Meson-Ninja
http://mesonbuild.com
https://ninja-build.org/


** GIT
http://rogerdudler.github.io/git-guide/


** GSTREAMER
Upstream : git://anongit.freedesktop.org/gstreamer/
           https://cgit.freedesktop.org/gstreamer/
Mirrored : https://github.com/GStreamer

FAQ
http://gstreamer.freedesktop.org/data/doc/gstreamer/head/faq/html/

DOCS
http://gstreamer.freedesktop.org/documentation

 GLib
 https://developer.gnome.org/glib/stable/

 GObject
 https://developer.gnome.org/gobject/stable/
>>>  https://developer.gnome.org/gobject/stable/chapter-gobject.html

*** Cerbero
Upstream : git://anongit.freedesktop.org/gstreamer/cerbero
Mirrored : https://github.com/GStreamer/cerbero

Doc
https://github.com/centricular/cerbero-docs/blob/master/start.md
https://gstreamer.freedesktop.org/documentation/installing/building-from-source-using-cerbero.html


** HARD DISK HEALTH
sudo apt get install smartmontools
smartctl 
https://www.smartmontools.org/
https://wiki.archlinux.org/index.php/S.M.A.R.T.


** LINUX

*** Secure programming
https://www.dwheeler.com/secure-programs/Secure-Programs-HOWTO/index.html

** RASPBERRYPI 
https://www.raspberrypi.org/documentation/linux/kernel/README.md

*** Building NOOBS from source

ERR : noob build fail: RCC: Error in 'icons.qrc': Cannot find file 'translation_ca.qm'
SLN :  ./buildroot/output/host/usr/bin/lrelease ./recovery/translation_*.ts

*** CONFIG
https://github.com/RPi-Distro/raspi-config

sudo raspi-config // /boot/config.txt
 user/password
 hostname
 ssh
 spi/i2c/serial/audio

vcgencmd get_config <config>

**** Initial Config
passwd #change default password
Edit .bashrs under /etc/skel
sudo adduser <username>
update-alternatives --set editor /usr/bin/vim.tiny
sudo visudo
<username>   ALL = NOPASSWD: ALL
sudo userdel -r pi
sudo reboot
#login with new <username>
sudo raspi-config
#check user/password
#change hostname
#enable ssh
#enable spi/i2c/serial/audio

***** DO Customisation script/patch-file for new installs

**** Audio
amixer cset numid=3 0 # 0:Auto 1:Analog 2:HDMI


*** STARTED DEVICE TREE
https://www.raspberrypi.org/documentation/configuration/device-tree.md

config.txt - Uncomment required external interfaces (SPI, I2C, I2S) and the peripherals that use them

*** PROJECTS

http://stevenhickson.blogspot.com/

**** SERVER

***** CLOUD - Owncloud
Open sourced. Mature. Has enterprise edition also.
https://owncloud.org/
http://www.techradar.com/how-to/computing/how-to-set-up-a-raspberry-pi-powered-cloud-service-1316017/2

***** DONE CLOUD - CloudNimbus
https://cloudnimbus.org/
Close sourced. Still in development.

***** SambaServer
https://www.howtogeek.com/139433/how-to-turn-a-raspberry-pi-into-a-low-power-network-storage-device/

sudo apt-get update

sudo apt-get install ntfs-3g
sudo fdisk -l
lsblk

sudo apt-get install samba samba-common-bin

sudo mkdir -m 1777 /srv/smb
sudo mount -t auto /dev/sda1 /srv/smb
sudo cp /etc/samba/smb.conf /etc/samba/smb.conf.$(date +%F)

workgroup = workgroup_name
wins support = yes
security = user

[SMB]
  comment = Samba share
  path = /srv/smb
  valid users = @users
  force group = users
  browseable = yes
  read only = no
  writeable = yes
  only guest = no
  create mask = 0777
  directory mask = 0777
  public = no

testparm

service samba restart
or
sudo /etc/init.d/samba restart
or
sudo service smbd restart
sudo service nmbd restart

smbpasswd -a root
smbpasswd -a pi

pdbedit -L #list samba users

smbclient -L localhost 

***** DONE GitServer
https://git-scm.com/book/en/v2/Git-on-the-Server-Getting-Git-on-a-Server

- SERVER:
passwd
sudo raspi-config // enable ssh etc
sudo apt-get update
sudo apt-get upgrade

- CLIENT:
ssh-keygen
scp ~/.ssh/id_rsa <username>@<ipaddr>:/tmp/

SERVER
sudo apt-get install git
sudo adduser git
su git
cd
mkdir .ssh
chmod 700 .ssh
touch .ssh/authorized_keys
chmod 600 .ssh/authorized_keys
cat /tmp/id_rsa_hom.pub >> .ssh/authorized_keys
sudo groupadd git-scm
sudo usermod -g git-scm git

sudo mkdir /srv/git
sudo chgrp git-scm /srv/git
sudo chmod 775 /srv/git

mkdir /srv/git/<project>.git
cd <project>.git
git init --bare --shared

- CLIENT:
cd <>
git config --local user.name "<>"
git config --local user.email "<>"
git init
echo -e ".gitignore\n*~\n" > .gitignore
git add .
git commit -m "Initial commit"
git remote add origin git@<>:/srv/git/gtd2.git
git push origin master

- SERVER
cat /etc/shells   # see if `git-shell` is already in there.  If not...
which git-shell   # make sure git-shell is installed on your system.
sudo nano /etc/shells  # and add the path to git-shell from last command
sudo chsh git -s $(which git-shell)





***** Webserver
How to set up a secure Raspberry Pi web server, mail server and Owncloud installation
https://www.pestmeester.nl/

**** Timelapse camera

**** Presentation


*** REMOTE CONNECTIVITY
https://www.raspberrypi.org/documentation/remote-access/access-over-Internet/README.md
**** Without port forwarding
https://www.dataplicity.com/ 1st device free, $2/mon
https://remote-iot.com/web/pricing.htm $5, 50 devices
**** VNC
https://www.raspberrypi.org/documentation/remote-access/vnc/README.md

*** SYSTEM
Standalone Boot process
https://github.com/raspberrypi/noobs/wiki/Standalone-partitioning-explained

Noob Partitioning
https://github.com/raspberrypi/noobs/wiki/Standalone-partitioning-explained


*** Serial Port
Rpi 3 onwards :
/dev/tty0 or 
/dev/serial0 -- maps to correct port irrespective of model
https://www.raspberrypi.org/documentation/configuration/uart.md
http://spellfoundry.com/2016/05/29/configuring-gpio-serial-port-raspbian-jessie-including-pi-3/
http://elinux.org/RPi_Serial_Connection


** CONSOLIDATE DATA

Hook old drive to Linux
Scanfor virus
Repeat

Get new drive
Transfer data
Format old drive and use for backups

https://askubuntu.com/questions/69363/mount-single-partition-from-image-of-entire-disk-device




